# Docker Compose file for setting up Kafka and Zookeeper
# Version of the docker-compose file format
version: '3.8'

# Define the services (containers) to run
services:
  # Zookeeper service, which Kafka depends on
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka message broker service
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    # The kafka container depends on the zookeeper container.
    # This ensures zookeeper is started before kafka.
    depends_on:
      - zookeeper
    ports:
      # Expose Kafka's port 9092 to the host machine so our
      # Python script can connect to it.
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # This configuration allows clients (like our Python script) to connect to Kafka
      # from outside the Docker container network (i.e., from our host machine).
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
